import java.util.HashMap;
import java.util.Map;

public class RockPaperScissorsPart2 {

    public static void main(String[] args) {

        String input = "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "C X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "B Y\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "B X\n" +
                "B X\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Z\n" +
                "B X\n" +
                "B X\n" +
                "B Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "C Z\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "B Y\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "B Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "B X\n" +
                "C X\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "C Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "B Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C Z\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B X\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "C Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "B Y\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "C X\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "C X\n" +
                "B X\n" +
                "B Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "B Y\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "B X\n" +
                "B Y\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Y\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "B Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "C X\n" +
                "B Y\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "C X\n" +
                "B X\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Y\n" +
                "C X\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "C X\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "C X\n" +
                "B X\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "B X\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Z\n" +
                "B Z\n" +
                "B X\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Z\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C X\n" +
                "B Y\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "B X\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "B Y\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B X\n" +
                "B Y\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "B Y\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C Z\n" +
                "C X\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "C X\n" +
                "A Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "B X\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "C Y";
        System.out.println(findScore(input));
    }

    public static long findScore(String input) {
        Map<String, Integer> abcMap = new HashMap<>();
        abcMap.put("A", 1);
        abcMap.put("B", 2);
        abcMap.put("C", 3);

        long result = 0;
        String[] strs = input.split("\n");
        for (String str : strs) {

            String[] s = str.split(" ");
            String first = s[0];
            String second = s[1];
            result = result + getRequiredShapeScore(first, second, abcMap);
        }
        return result;
    }

    //13187
    private static int getRequiredShapeScore(String opponentChoice, String resultNeeded,
                                             Map<String, Integer> choiceScoreMap) {
        // 1->3->2
        // r->s->p
        // going for draw
        if (resultNeeded.equals("Y")) {
            return choiceScoreMap.get(opponentChoice) + 3;
        }

        if (opponentChoice.equals("A")) {
            // lose
            if (resultNeeded.equals("X")) {
                return choiceScoreMap.get("C");
            } else {
                return choiceScoreMap.get("B") + 6;
            }
        }

        if (opponentChoice.equals("B")) {
            if (resultNeeded.equals("X")) {
                return choiceScoreMap.get("A");
            } else {
                return choiceScoreMap.get("C") + 6;
            }
        }

        if (opponentChoice.equals("C")) {
            if (resultNeeded.equals("X")) {
                return choiceScoreMap.get("B");
            } else {
                return choiceScoreMap.get("A") + 6;
            }
        }

        return 0;
    }

}

//15022
