import java.util.HashMap;
import java.util.Map;

public class RockPaperScissorsPart1 {

    public static void main(String[] args) {

        String input = "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "C X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "B Y\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "B X\n" +
                "B X\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Z\n" +
                "B X\n" +
                "B X\n" +
                "B Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "C Z\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "B Y\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "B Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "B X\n" +
                "C X\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "C Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "B Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C Z\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B X\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "C Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "B Y\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "C X\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "C X\n" +
                "B X\n" +
                "B Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "B Y\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "B X\n" +
                "B Y\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A X\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Y\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "B Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "C X\n" +
                "B Y\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "C X\n" +
                "B X\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Y\n" +
                "C X\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "C X\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "C X\n" +
                "B X\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "B X\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Z\n" +
                "B Z\n" +
                "B X\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Z\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C X\n" +
                "B Y\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "B X\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "B Y\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B X\n" +
                "B Y\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "B X\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "B Y\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C Z\n" +
                "C X\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "C X\n" +
                "A Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Z\n" +
                "B X\n" +
                "B Z\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "B X\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "C Y";
        System.out.println(findScore(input));
    }

    public static long findScore(String input) {

        Map<String, Integer> xyzMap = new HashMap<>();
        xyzMap.put("X", 1);
        xyzMap.put("Y", 2);
        xyzMap.put("Z", 3);
        long result = 0;

        String[] strs = input.split("\n");
        for (String str : strs) {

            String[] s = str.split(" ");
            String first = s[0];
            String second = s[1];

            if (whoWin(first, second).equals("b")) {

                result = result + xyzMap.get(second) + 6;
            } else if (whoWin(first, second).equals("a")) {
                result = result + xyzMap.get(second);
            } else if (whoWin(first, second).equals("-")) {
                result = result + xyzMap.get(second) + 3;
            }
        }
        return result;
    }

    private static String whoWin(String a, String b) {

        // draw scenarios
        if ((a.equals("A") && b.equals("X")) || (a.equals("B") && b.equals("Y")) || (a.equals("C") && b.equals("Z"))) {
            return "-";
        }
        // a winning scenarios
        if (a.equals("B") && b.equals("X")) {
            return "a";
        }
        if (a.equals("A") && b.equals("Z")) {
            return "a";
        }

        if (a.equals("C") && b.equals("Y")) {
            return "a";
        }

        // else b wins
        return "b";
    }
}
