public final class InputDay5 {

    public static final String SMALL_INPUT = "    [D]    \n" +
            "[N] [C]    \n" +
            "[Z] [M] [P]\n" +
            " 1   2   3 \n" +
            "\n" +
            "move 1 from 2 to 1\n" +
            "move 3 from 1 to 3\n" +
            "move 2 from 2 to 1\n" +
            "move 1 from 1 to 2";
    public static final String LARGE_INPUT = "                [B]     [L]     [S]\n" +
            "        [Q] [J] [C]     [W]     [F]\n" +
            "    [F] [T] [B] [D]     [P]     [P]\n" +
            "    [S] [J] [Z] [T]     [B] [C] [H]\n" +
            "    [L] [H] [H] [Z] [G] [Z] [G] [R]\n" +
            "[R] [H] [D] [R] [F] [C] [V] [Q] [T]\n" +
            "[C] [J] [M] [G] [P] [H] [N] [J] [D]\n" +
            "[H] [B] [R] [S] [R] [T] [S] [R] [L]\n" +
            " 1   2   3   4   5   6   7   8   9 \n" +
            "\n" +
            "move 8 from 7 to 1\n" +
            "move 9 from 1 to 9\n" +
            "move 4 from 5 to 4\n" +
            "move 4 from 6 to 1\n" +
            "move 3 from 8 to 5\n" +
            "move 6 from 5 to 9\n" +
            "move 1 from 5 to 1\n" +
            "move 4 from 4 to 9\n" +
            "move 7 from 3 to 7\n" +
            "move 6 from 7 to 3\n" +
            "move 1 from 8 to 7\n" +
            "move 2 from 7 to 6\n" +
            "move 1 from 8 to 9\n" +
            "move 1 from 6 to 3\n" +
            "move 4 from 3 to 5\n" +
            "move 5 from 1 to 3\n" +
            "move 1 from 1 to 8\n" +
            "move 2 from 3 to 4\n" +
            "move 1 from 4 to 1\n" +
            "move 7 from 9 to 2\n" +
            "move 1 from 6 to 3\n" +
            "move 2 from 1 to 9\n" +
            "move 20 from 9 to 7\n" +
            "move 6 from 4 to 9\n" +
            "move 1 from 2 to 9\n" +
            "move 6 from 9 to 4\n" +
            "move 1 from 4 to 6\n" +
            "move 1 from 8 to 6\n" +
            "move 1 from 4 to 7\n" +
            "move 5 from 2 to 3\n" +
            "move 2 from 6 to 4\n" +
            "move 3 from 9 to 5\n" +
            "move 5 from 3 to 5\n" +
            "move 3 from 3 to 8\n" +
            "move 3 from 5 to 6\n" +
            "move 1 from 9 to 8\n" +
            "move 5 from 4 to 5\n" +
            "move 3 from 4 to 9\n" +
            "move 1 from 8 to 2\n" +
            "move 2 from 8 to 2\n" +
            "move 11 from 5 to 6\n" +
            "move 16 from 7 to 1\n" +
            "move 2 from 1 to 7\n" +
            "move 14 from 6 to 1\n" +
            "move 11 from 1 to 6\n" +
            "move 2 from 1 to 4\n" +
            "move 4 from 3 to 4\n" +
            "move 9 from 2 to 4\n" +
            "move 2 from 4 to 8\n" +
            "move 2 from 5 to 3\n" +
            "move 9 from 4 to 7\n" +
            "move 2 from 3 to 2\n" +
            "move 1 from 2 to 7\n" +
            "move 1 from 8 to 4\n" +
            "move 4 from 1 to 4\n" +
            "move 1 from 9 to 1\n" +
            "move 7 from 4 to 7\n" +
            "move 2 from 6 to 5\n" +
            "move 1 from 8 to 6\n" +
            "move 1 from 4 to 2\n" +
            "move 10 from 1 to 6\n" +
            "move 5 from 7 to 3\n" +
            "move 1 from 4 to 7\n" +
            "move 2 from 1 to 2\n" +
            "move 2 from 2 to 4\n" +
            "move 4 from 3 to 4\n" +
            "move 18 from 7 to 6\n" +
            "move 6 from 6 to 4\n" +
            "move 1 from 7 to 4\n" +
            "move 1 from 7 to 6\n" +
            "move 11 from 4 to 5\n" +
            "move 14 from 5 to 9\n" +
            "move 1 from 8 to 7\n" +
            "move 8 from 6 to 2\n" +
            "move 2 from 4 to 5\n" +
            "move 7 from 9 to 1\n" +
            "move 6 from 9 to 7\n" +
            "move 5 from 1 to 8\n" +
            "move 1 from 3 to 6\n" +
            "move 10 from 6 to 3\n" +
            "move 1 from 9 to 6\n" +
            "move 1 from 5 to 4\n" +
            "move 4 from 3 to 8\n" +
            "move 1 from 5 to 9\n" +
            "move 9 from 2 to 3\n" +
            "move 1 from 9 to 5\n" +
            "move 4 from 8 to 4\n" +
            "move 1 from 5 to 3\n" +
            "move 5 from 8 to 7\n" +
            "move 5 from 7 to 2\n" +
            "move 3 from 4 to 1\n" +
            "move 8 from 6 to 5\n" +
            "move 1 from 7 to 9\n" +
            "move 4 from 1 to 3\n" +
            "move 2 from 4 to 6\n" +
            "move 5 from 5 to 2\n" +
            "move 4 from 6 to 9\n" +
            "move 1 from 1 to 2\n" +
            "move 1 from 5 to 6\n" +
            "move 7 from 2 to 8\n" +
            "move 5 from 6 to 8\n" +
            "move 4 from 7 to 9\n" +
            "move 15 from 3 to 9\n" +
            "move 1 from 7 to 3\n" +
            "move 1 from 5 to 3\n" +
            "move 6 from 2 to 6\n" +
            "move 1 from 5 to 2\n" +
            "move 2 from 3 to 9\n" +
            "move 1 from 6 to 8\n" +
            "move 5 from 8 to 9\n" +
            "move 2 from 3 to 8\n" +
            "move 3 from 3 to 6\n" +
            "move 11 from 9 to 4\n" +
            "move 1 from 2 to 1\n" +
            "move 2 from 8 to 4\n" +
            "move 1 from 1 to 4\n" +
            "move 7 from 4 to 7\n" +
            "move 9 from 6 to 3\n" +
            "move 4 from 7 to 8\n" +
            "move 4 from 7 to 6\n" +
            "move 19 from 9 to 4\n" +
            "move 7 from 8 to 5\n" +
            "move 5 from 3 to 6\n" +
            "move 6 from 6 to 9\n" +
            "move 3 from 3 to 5\n" +
            "move 1 from 3 to 9\n" +
            "move 8 from 4 to 5\n" +
            "move 2 from 9 to 6\n" +
            "move 3 from 8 to 2\n" +
            "move 1 from 8 to 4\n" +
            "move 1 from 2 to 5\n" +
            "move 19 from 4 to 1\n" +
            "move 2 from 5 to 7\n" +
            "move 2 from 2 to 4\n" +
            "move 13 from 5 to 2\n" +
            "move 1 from 5 to 1\n" +
            "move 2 from 6 to 9\n" +
            "move 1 from 8 to 7\n" +
            "move 9 from 9 to 3\n" +
            "move 2 from 3 to 8\n" +
            "move 1 from 4 to 2\n" +
            "move 5 from 6 to 7\n" +
            "move 1 from 4 to 6\n" +
            "move 2 from 8 to 7\n" +
            "move 7 from 1 to 5\n" +
            "move 1 from 6 to 7\n" +
            "move 10 from 1 to 8\n" +
            "move 1 from 1 to 3\n" +
            "move 1 from 1 to 2\n" +
            "move 6 from 5 to 3\n" +
            "move 4 from 5 to 3\n" +
            "move 5 from 7 to 1\n" +
            "move 3 from 1 to 2\n" +
            "move 4 from 7 to 5\n" +
            "move 8 from 3 to 6\n" +
            "move 2 from 1 to 7\n" +
            "move 4 from 5 to 8\n" +
            "move 7 from 3 to 5\n" +
            "move 3 from 7 to 2\n" +
            "move 1 from 7 to 3\n" +
            "move 12 from 2 to 8\n" +
            "move 23 from 8 to 2\n" +
            "move 16 from 2 to 6\n" +
            "move 1 from 9 to 6\n" +
            "move 7 from 5 to 7\n" +
            "move 7 from 2 to 4\n" +
            "move 2 from 3 to 8\n" +
            "move 1 from 1 to 9\n" +
            "move 5 from 8 to 1\n" +
            "move 2 from 3 to 9\n" +
            "move 2 from 7 to 1\n" +
            "move 4 from 1 to 3\n" +
            "move 4 from 7 to 2\n" +
            "move 2 from 1 to 4\n" +
            "move 11 from 2 to 9\n" +
            "move 3 from 3 to 4\n" +
            "move 1 from 9 to 1\n" +
            "move 2 from 2 to 7\n" +
            "move 4 from 4 to 8\n" +
            "move 2 from 9 to 5\n" +
            "move 2 from 5 to 7\n" +
            "move 4 from 4 to 6\n" +
            "move 1 from 3 to 8\n" +
            "move 1 from 9 to 8\n" +
            "move 4 from 4 to 2\n" +
            "move 2 from 1 to 3\n" +
            "move 1 from 8 to 4\n" +
            "move 2 from 3 to 5\n" +
            "move 3 from 9 to 7\n" +
            "move 2 from 8 to 9\n" +
            "move 1 from 9 to 6\n" +
            "move 2 from 7 to 3\n" +
            "move 2 from 8 to 1\n" +
            "move 1 from 4 to 9\n" +
            "move 18 from 6 to 2\n" +
            "move 1 from 6 to 5\n" +
            "move 1 from 5 to 9\n" +
            "move 18 from 2 to 3\n" +
            "move 1 from 8 to 7\n" +
            "move 2 from 5 to 9\n" +
            "move 1 from 1 to 4\n" +
            "move 3 from 2 to 1\n" +
            "move 9 from 9 to 4\n" +
            "move 7 from 4 to 6\n" +
            "move 2 from 7 to 3\n" +
            "move 2 from 4 to 9\n" +
            "move 7 from 6 to 7\n" +
            "move 3 from 7 to 2\n" +
            "move 7 from 6 to 3\n" +
            "move 2 from 6 to 9\n" +
            "move 24 from 3 to 9\n" +
            "move 2 from 6 to 8\n" +
            "move 1 from 4 to 2\n" +
            "move 2 from 8 to 5\n" +
            "move 31 from 9 to 3\n" +
            "move 6 from 7 to 4\n" +
            "move 35 from 3 to 7\n" +
            "move 1 from 1 to 8\n" +
            "move 1 from 5 to 7\n" +
            "move 1 from 5 to 4\n" +
            "move 1 from 3 to 9\n" +
            "move 1 from 8 to 2\n" +
            "move 3 from 1 to 7\n" +
            "move 7 from 4 to 5\n" +
            "move 1 from 9 to 8\n" +
            "move 4 from 5 to 6\n" +
            "move 2 from 5 to 2\n" +
            "move 6 from 2 to 5\n" +
            "move 2 from 5 to 7\n" +
            "move 2 from 2 to 1\n" +
            "move 2 from 5 to 4\n" +
            "move 1 from 8 to 4\n" +
            "move 3 from 4 to 6\n" +
            "move 4 from 6 to 7\n" +
            "move 1 from 5 to 2\n" +
            "move 2 from 6 to 9\n" +
            "move 1 from 6 to 4\n" +
            "move 1 from 4 to 8\n" +
            "move 2 from 9 to 6\n" +
            "move 1 from 8 to 9\n" +
            "move 34 from 7 to 9\n" +
            "move 6 from 7 to 3\n" +
            "move 1 from 7 to 2\n" +
            "move 1 from 5 to 8\n" +
            "move 1 from 8 to 6\n" +
            "move 6 from 7 to 4\n" +
            "move 1 from 7 to 3\n" +
            "move 7 from 3 to 5\n" +
            "move 6 from 4 to 6\n" +
            "move 31 from 9 to 1\n" +
            "move 3 from 5 to 7\n" +
            "move 24 from 1 to 3\n" +
            "move 1 from 2 to 4\n" +
            "move 3 from 9 to 1\n" +
            "move 14 from 3 to 5\n" +
            "move 1 from 4 to 3\n" +
            "move 1 from 9 to 7\n" +
            "move 8 from 3 to 7\n" +
            "move 1 from 2 to 9\n" +
            "move 7 from 1 to 5\n" +
            "move 3 from 6 to 8\n" +
            "move 3 from 6 to 1\n" +
            "move 1 from 1 to 3\n" +
            "move 4 from 3 to 2\n" +
            "move 4 from 2 to 3\n" +
            "move 2 from 5 to 1\n" +
            "move 9 from 7 to 4\n" +
            "move 1 from 6 to 5\n" +
            "move 1 from 1 to 7\n" +
            "move 3 from 8 to 9\n" +
            "move 5 from 4 to 2\n" +
            "move 3 from 2 to 3\n" +
            "move 1 from 2 to 3\n" +
            "move 2 from 4 to 1\n" +
            "move 2 from 9 to 4\n" +
            "move 1 from 9 to 3\n" +
            "move 1 from 6 to 1\n" +
            "move 1 from 9 to 6\n" +
            "move 25 from 5 to 4\n" +
            "move 4 from 1 to 9\n" +
            "move 2 from 3 to 7\n" +
            "move 2 from 6 to 9\n" +
            "move 2 from 9 to 5\n" +
            "move 6 from 7 to 1\n" +
            "move 5 from 3 to 6\n" +
            "move 10 from 4 to 3\n" +
            "move 10 from 4 to 8\n" +
            "move 2 from 4 to 2\n" +
            "move 5 from 1 to 9\n" +
            "move 2 from 6 to 4\n" +
            "move 6 from 9 to 6\n" +
            "move 7 from 6 to 4\n" +
            "move 3 from 9 to 4\n" +
            "move 3 from 2 to 4\n" +
            "move 4 from 3 to 8\n" +
            "move 2 from 5 to 3\n" +
            "move 10 from 4 to 9\n" +
            "move 4 from 9 to 7\n" +
            "move 5 from 9 to 5\n" +
            "move 4 from 5 to 1\n" +
            "move 9 from 4 to 6\n" +
            "move 10 from 1 to 3\n" +
            "move 1 from 5 to 4\n" +
            "move 3 from 4 to 5\n" +
            "move 2 from 5 to 7\n" +
            "move 1 from 7 to 3\n" +
            "move 1 from 6 to 9\n" +
            "move 11 from 8 to 6\n" +
            "move 14 from 6 to 5\n" +
            "move 1 from 4 to 7\n" +
            "move 7 from 5 to 3\n" +
            "move 3 from 5 to 4\n" +
            "move 2 from 9 to 5\n" +
            "move 2 from 4 to 3\n" +
            "move 2 from 7 to 4\n" +
            "move 11 from 3 to 9\n" +
            "move 2 from 8 to 2\n" +
            "move 2 from 2 to 3\n" +
            "move 1 from 8 to 2\n" +
            "move 1 from 2 to 9\n" +
            "move 3 from 4 to 5\n" +
            "move 2 from 6 to 9\n" +
            "move 1 from 1 to 8\n" +
            "move 10 from 9 to 7\n" +
            "move 2 from 9 to 3\n" +
            "move 23 from 3 to 9\n" +
            "move 4 from 6 to 4\n" +
            "move 9 from 5 to 6\n" +
            "move 1 from 5 to 3\n" +
            "move 5 from 6 to 7\n" +
            "move 1 from 1 to 7\n" +
            "move 1 from 3 to 9\n" +
            "move 4 from 6 to 7\n" +
            "move 1 from 8 to 7\n" +
            "move 1 from 7 to 5\n" +
            "move 1 from 5 to 1\n" +
            "move 12 from 7 to 6\n" +
            "move 9 from 9 to 3\n" +
            "move 6 from 6 to 4\n" +
            "move 8 from 7 to 3\n" +
            "move 3 from 7 to 4\n" +
            "move 6 from 3 to 1\n" +
            "move 10 from 4 to 8\n" +
            "move 10 from 8 to 7\n" +
            "move 2 from 3 to 7\n" +
            "move 9 from 3 to 8\n" +
            "move 2 from 6 to 3\n" +
            "move 10 from 7 to 1\n" +
            "move 3 from 4 to 6\n" +
            "move 5 from 8 to 5\n" +
            "move 3 from 5 to 7\n" +
            "move 1 from 3 to 2\n" +
            "move 1 from 2 to 6\n" +
            "move 6 from 9 to 1\n" +
            "move 12 from 1 to 3\n" +
            "move 3 from 6 to 9\n" +
            "move 3 from 1 to 7\n" +
            "move 1 from 3 to 2\n" +
            "move 7 from 1 to 7\n" +
            "move 1 from 2 to 7\n" +
            "move 2 from 6 to 4\n" +
            "move 1 from 4 to 5\n" +
            "move 3 from 8 to 7\n" +
            "move 2 from 6 to 3\n" +
            "move 2 from 6 to 1\n" +
            "move 1 from 3 to 8\n" +
            "move 5 from 3 to 4\n" +
            "move 2 from 8 to 5\n" +
            "move 14 from 7 to 4\n" +
            "move 1 from 3 to 2\n" +
            "move 1 from 3 to 7\n" +
            "move 7 from 7 to 4\n" +
            "move 2 from 5 to 3\n" +
            "move 2 from 1 to 4\n" +
            "move 9 from 4 to 6\n" +
            "move 1 from 1 to 2\n" +
            "move 4 from 9 to 4\n" +
            "move 8 from 9 to 3\n" +
            "move 2 from 2 to 7\n" +
            "move 13 from 4 to 8\n" +
            "move 4 from 4 to 1\n" +
            "move 2 from 7 to 6\n" +
            "move 12 from 3 to 2\n" +
            "move 11 from 2 to 9\n" +
            "move 6 from 4 to 9\n" +
            "move 18 from 9 to 4\n" +
            "move 2 from 1 to 6\n" +
            "move 6 from 8 to 1\n" +
            "move 13 from 6 to 5\n" +
            "move 8 from 4 to 5\n" +
            "move 1 from 2 to 9\n" +
            "move 8 from 1 to 4\n" +
            "move 7 from 4 to 8\n" +
            "move 4 from 3 to 5\n" +
            "move 10 from 8 to 5\n" +
            "move 13 from 5 to 8\n" +
            "move 12 from 4 to 5\n" +
            "move 2 from 9 to 8\n" +
            "move 29 from 5 to 9\n" +
            "move 24 from 9 to 2\n" +
            "move 23 from 2 to 4\n" +
            "move 5 from 9 to 2\n" +
            "move 7 from 5 to 7\n" +
            "move 1 from 5 to 1\n" +
            "move 7 from 4 to 8\n" +
            "move 14 from 8 to 1\n" +
            "move 5 from 2 to 6\n" +
            "move 16 from 4 to 7\n" +
            "move 8 from 1 to 6\n" +
            "move 1 from 2 to 8\n" +
            "move 20 from 7 to 6\n" +
            "move 11 from 6 to 4\n" +
            "move 3 from 1 to 5\n" +
            "move 3 from 4 to 3\n" +
            "move 8 from 4 to 9\n" +
            "move 8 from 6 to 1\n" +
            "move 2 from 1 to 4\n" +
            "move 3 from 5 to 2\n" +
            "move 12 from 8 to 2\n" +
            "move 1 from 7 to 1\n" +
            "move 1 from 3 to 5\n" +
            "move 1 from 7 to 8\n" +
            "move 1 from 7 to 3\n" +
            "move 12 from 2 to 8\n" +
            "move 13 from 6 to 4\n" +
            "move 2 from 1 to 9\n" +
            "move 3 from 2 to 6\n" +
            "move 3 from 9 to 7\n" +
            "move 5 from 9 to 1\n" +
            "move 4 from 6 to 4\n" +
            "move 2 from 3 to 6\n" +
            "move 1 from 5 to 9\n" +
            "move 1 from 6 to 7\n" +
            "move 9 from 1 to 5\n" +
            "move 11 from 8 to 3\n" +
            "move 1 from 6 to 8\n" +
            "move 3 from 7 to 1\n" +
            "move 1 from 8 to 7\n" +
            "move 2 from 8 to 9\n" +
            "move 7 from 1 to 2\n" +
            "move 17 from 4 to 7\n" +
            "move 1 from 8 to 6\n" +
            "move 4 from 7 to 2\n" +
            "move 4 from 9 to 7\n" +
            "move 4 from 2 to 3\n" +
            "move 1 from 1 to 4\n" +
            "move 2 from 4 to 3\n" +
            "move 9 from 5 to 4\n" +
            "move 1 from 6 to 8\n" +
            "move 6 from 2 to 1\n" +
            "move 5 from 1 to 9\n" +
            "move 9 from 4 to 3\n" +
            "move 1 from 4 to 6\n" +
            "move 2 from 9 to 7\n" +
            "move 1 from 1 to 5\n" +
            "move 1 from 2 to 7\n" +
            "move 1 from 8 to 9\n" +
            "move 1 from 6 to 8\n" +
            "move 1 from 5 to 4\n" +
            "move 1 from 8 to 7\n" +
            "move 23 from 3 to 7\n" +
            "move 36 from 7 to 6\n" +
            "move 33 from 6 to 1\n" +
            "move 1 from 4 to 8\n" +
            "move 7 from 1 to 5\n" +
            "move 1 from 8 to 1\n" +
            "move 3 from 7 to 2\n" +
            "move 24 from 1 to 3\n" +
            "move 7 from 7 to 3\n" +
            "move 3 from 5 to 1\n" +
            "move 4 from 5 to 3\n" +
            "move 1 from 9 to 8\n" +
            "move 2 from 9 to 6\n" +
            "move 1 from 8 to 5\n" +
            "move 3 from 2 to 5\n" +
            "move 30 from 3 to 5\n" +
            "move 1 from 6 to 7\n" +
            "move 6 from 1 to 8\n" +
            "move 7 from 3 to 2\n" +
            "move 1 from 7 to 5\n" +
            "move 2 from 3 to 2\n" +
            "move 2 from 6 to 8\n" +
            "move 1 from 6 to 1\n" +
            "move 7 from 5 to 8\n" +
            "move 8 from 8 to 7\n" +
            "move 20 from 5 to 8\n" +
            "move 2 from 9 to 7\n" +
            "move 8 from 2 to 1\n" +
            "move 7 from 7 to 3\n" +
            "move 1 from 2 to 1\n" +
            "move 3 from 7 to 9\n" +
            "move 4 from 8 to 3\n" +
            "move 5 from 5 to 6\n" +
            "move 1 from 5 to 9\n" +
            "move 4 from 9 to 4\n" +
            "move 1 from 5 to 9\n" +
            "move 2 from 3 to 6\n" +
            "move 1 from 5 to 8\n" +
            "move 7 from 6 to 3\n" +
            "move 1 from 4 to 1\n" +
            "move 7 from 3 to 2\n" +
            "move 3 from 3 to 5\n" +
            "move 2 from 4 to 7";
}
