public final class InputDay3 {

    public static final String SMALL_INPUT = "vJrwpWtwJgWrhcsFMMfFFhFp\n" +
            "jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL\n" +
            "PmmdzqPrVvPwwTWBwg\n" +
            "wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn\n" +
            "ttgJtRGJQctTZtZT\n" +
            "CrZsJsPPZsGzwwsLwLmpwMDw";
    public static final String LARGE_INPUT = "hDsDDttbhsmshNNWMNWGbTNqZq\n" +
            "VQfjnlFvnQFRdZWdVtqMGdWW\n" +
            "zvvvRnFFfjjlRBlBPzgQgRvvmtrmhHcptLHCDhcHHmLsBmsB\n" +
            "FrzFvvdTDcTnmTzdDTTzdvWmjhgVPrhSljSQSPwPjPjPjSVC\n" +
            "sMsGbqGsbbRqRbBMBGRMbLpNSSpjhlQljHVClhjgPjjPhlVp\n" +
            "sNbGtJbMfssNtvcnWFVmnvDd\n" +
            "TNfmdFJmfdZMQffVRQVV\n" +
            "jVHBCcDSjWrMZjvg\n" +
            "SShSbCGpcBtBtwtVLJJddmtLmT\n" +
            "CtpNftbNWbtSJDHqGZJFLfLr\n" +
            "dPsHlsRBHcZdqDFDZwwJ\n" +
            "snjVlvTPlPjVlQlHWjpSmzgNNzSmtpSm\n" +
            "qhZtSVqCqThGcGzZnnfZcB\n" +
            "WbddWbDwrBzcpzHpBb\n" +
            "DBBMFWRJDrDFWLWljCqjQjFvtCsqTjqs\n" +
            "vhFTzRzzTmPvbplWFtQttQQZtZhMZqcqSQ\n" +
            "fJVCfDfJNCLDwJNGmssZgwqgZcmtgcms\n" +
            "VmdVNLHGGVDBdfLCHnLGHnbWpTplWbddRTlzplWPpbFp\n" +
            "smwtNVqRjNmZjZBDSvzSzl\n" +
            "FnTJFcTTFccCrJGTLncdCCcPJZfBBDSlSJwZDlggSffvgSSf\n" +
            "FWTFGLFWLCPWrCnFnQWNbQVVwphhmHHbptVsss\n" +
            "BrrgrtgfBpPFhhgMWq\n" +
            "ZGvsvDGClvsSRScpGBhPphWMPhhTNh\n" +
            "SBSBdBZCcdwHrVQwQr\n" +
            "qmFqdVtqsVdzqGbwMJwGPpmPHM\n" +
            "ZjTjLQLLDrrLjcFhlfrGHppfbJwGpMMpGHwRCC\n" +
            "BTlZjrBBBcLTcDrjBlThWBjBtWNqnSzSnsSdvsFggNnqVVnv\n" +
            "zVvmjGgpcJnbTTTJHRHSRb\n" +
            "NPFrFQfCLPrdRlbtQRRvBtHb\n" +
            "frMLqPFMrfrPLCwqqNvjczwwnmwggGmssnmnnm\n" +
            "HbFJhhshsffcvslmGmLFrQBrlFTG\n" +
            "jNRPwwPjSPCdCdvRzRBTlRzmGrmB\n" +
            "nCSWdNjCCPqvtttZnDscth\n" +
            "ScSrRTPcSSDRWSptWcdmmWGbmGGLmLJvNJNbbJ\n" +
            "flzHjFpZjFfjjgszjlqzJNnnvsmbMmGvJLNNbmJv\n" +
            "jFZFVpffpVlqfQhgtTwcTVtrTcRBwBTD\n" +
            "rHrdGSMSSbZbjShj\n" +
            "qZfDBBvllvvWLtqbbQwhJjbtwbnQgN\n" +
            "WzWlzZmLWBLZLzCzrHMVcRrMRFRCCccF\n" +
            "BzdplppDlBBrqWnjFMBWqNWq\n" +
            "whZhZSSHhhVSrvSgHPvgvjnFTPsFFnnNTcjTFnTTsc\n" +
            "HLCwVSfZLffSHhLvwtQbJbrdGlRRrGdmpztG\n" +
            "grDFfDlfCftCzCfNztclNFrBNQjbZjJjjPPVsjNvsbvPsj\n" +
            "HwwTpGpRwMdpHWhvjzVsPJjJGVvVZs\n" +
            "ShphRpwzMWdpHdwWHwMpnHwLDmmgcLCCDtLDCCSlcgcfCD\n" +
            "ccqqLLqCqTSlZMLQMllZTvnNfjddttmmDpRJjvhfpfthRmdf\n" +
            "rbVssWwggFrGsWzPbVFGJpftQRPDmQDpdPmdJmfR\n" +
            "bBHWWHzWHWWHrsVbsFgwbFqqMLTnBclTMMSnLnqLqMQZ\n" +
            "CcSPGCCPrdPtdjcsBLDghbVLhqDl\n" +
            "vMJwTHzPvzVwqBBDblls\n" +
            "QNvMFfRMJHPZHjnfWmdftSjSnp\n" +
            "dnBCPhhBCrQfChdbNVGLszzDzVDsTbWT\n" +
            "HgcJgpppPqqHwPwJSczVzDssNNVWTtqVVGts\n" +
            "JHRFpjFccplcRwPJpHPScpMPQmCdBQQfQjjhCfBCrQQvdmnn\n" +
            "rQGmVRLRbDRHmmZLGBGVLHBVFspSstWWWNJcsgpQTSsNppJS\n" +
            "qlldhPdfCgnspJFWCFsFNT\n" +
            "jMMzwndfhnwPfqPMjgjMVBrGBmrHDHLZbjRGHbHj\n" +
            "wzpZfzHRSRfzgHfffZwwStCtSrBhBBCTrtFhhBFG\n" +
            "QPjQQQDcDWJNFWtrtWrGmTCMtmBW\n" +
            "lDvvDQcdjQcQLvlDwnpFgbbznZZglZsl\n" +
            "RfMFTMFrVrSRFPlFSfVlHpLqgzpHBLzHBBVzVpHG\n" +
            "CchbhcwdmdJmwJJtGgnqzppLmGGBQqQp\n" +
            "hCsstCJwLvMRvsZsTR\n" +
            "fQlfMlNClQhhZhrlWrWw\n" +
            "njDbnTDTBtGjmrGvSh\n" +
            "bgshBdBcDbTTdnnnTqcqLgqfpfQppCsCMsHHVVpHHNCHFF\n" +
            "PbCnTbzJnqQNzbbTNDdpwcmjDmwjGQjccw\n" +
            "hWgvSdLvwcGjSpSm\n" +
            "vVfrFvvhHFTZndJq\n" +
            "FFvRVCRqVRcfsDLrgqGNWjjHfhQQzGWjQHzN\n" +
            "ppJPBwplwSBJTmPpTzWWStzHHjNNLNzHNh\n" +
            "wnwMPbLJMJllJJwBmJmnLVvCvsCsbFgDrRrsCsvrqc\n" +
            "jqHgVgdgGQttWCtNqNflmllgFnfDnmFFlpcl\n" +
            "TZZsrrwwhwrsrZRGmhcfSnhGlmSFcf\n" +
            "rsLvvbJPPLBGPCQqHWtMCMHN\n" +
            "WzzBpCBpMsBpCvCfsgnPPfHgbfFNfF\n" +
            "jtdTLLjGTGjDjLbbbGlDLLLmfFgmmfgrPrgmNPHSnnNnqFSq\n" +
            "jbRRbjlwlRVpvWwvzBpB\n" +
            "qpwzCzCznFznTcCvrcrvVcLb\n" +
            "cPmNMHSlMsLfvWgsrWvL\n" +
            "mMHGPDMBGSGPHlPBcBPzznnzpdQFBjqRFdwdnn\n" +
            "QGZLJzmJrZgZzZhNQFqDWlWPWDFCWNRlPW\n" +
            "hMMbhVbhHWCsPWCMRs\n" +
            "BwjbSHVBVvfcTfZgZzQhrzdGrt\n" +
            "cvPTjfDPpDmmBjbQjZMdlBZj\n" +
            "CHNnghNChVzNgrFVwCMJLMMMMMQQdbLZ\n" +
            "FNSzShrHhNnWgVnWfvfbpfpDGTfvsG\n" +
            "FFpVrZhpTlSQlQzTtRtZHfmPmJDbRtZJ\n" +
            "jNnwBLnWwBgNBNCwsNgsMsCLVfDWfmDJRffmRRtmfRmPDRtR\n" +
            "BnLdNdjnBNcLngdCVBndgllFlQrrpQlSSFrQphFcQq\n" +
            "JmVLJPMNjmVJpMLJSVmNQZZQZZrnTHqZQHTrTTMr\n" +
            "ltfdwChhwRdRswDDdnBQqqWNTqrrHrqZRr\n" +
            "dwdwwDwsGlhhDFtsCwhsJLcPmGPcGzSjSjjLzNPS\n" +
            "QgSbgQCLQSJFMccLFLVVzH\n" +
            "WBNffrBpBNdNRdWDfptBtdzWcMZZVPMVwHMmsVHFccHsDsVc\n" +
            "ptphRWrfGRGRnqlCSQvhqbCzJS\n" +
            "VvdMLMLMBMlVlVschsNpDGpdNsGc\n" +
            "tqFSmnmnnttGfDqNcfvNDD\n" +
            "nzRHnrwrrWRrrzHtbMlTMBjCvWLgBBMl\n" +
            "pCBlRvzwzlCzvZqqDwzmvgtsLsQdgZsgPNtdrsWrst\n" +
            "JbGjbGVGHSFbhbnhTShSTbQtQrPsLsHLQgNRtsgdQsLP\n" +
            "GnnbJbGMGbSjjbSbCzqlwMRRDzqzMBBv\n" +
            "TTVRJVMWMshSQtjSVTQJRQlcCBncJccdppnJcBBDngFpgP\n" +
            "frvfzfHrwzZNrtNwzzzZncCCZFdFFCgBDpPcBcBg\n" +
            "LwNGbqwvmvvtbNQjQlVVRWTGTQWM\n" +
            "RnggwVLRLDfCVZhfpDGGMGMGcGzGNHvv\n" +
            "jmmWBTSsBmFmSzctsqpccHvzpN\n" +
            "SBSrTblSQPbQhNwwZfPVdZPf\n" +
            "CCvCwzfNStLzfrbmMJbZMtlsbJMW\n" +
            "gPPPBqDjBcPFpVgBRbnMsVsbJZnWsdbSbM\n" +
            "qgDPHjHcPhpDRRpPBRpCGSLwvHQwGfzrHLGLTL\n" +
            "CLGqDZZLTdddPsdJpq\n" +
            "gbRbbnghnrWvgrdJdSTRSsVNJlld\n" +
            "hMnwrjnnjggvnLDwGffTfwCZZZ\n" +
            "NzJHbNHNNzJzgmHmzpQSvvLqbLsVVsVGvB\n" +
            "WtWhtWDdrZldDWrWTlZgppVVsqQTVQBqsGqBsQVp\n" +
            "jWjWRRRlPcHRwJgw\n" +
            "CCnnFTmnPCMCRNfnwGwdfzvwwl\n" +
            "VQQVShDSSshhDDtDLhjccGjLBBzBzlZflNZvwZzdwBzpSNNZ\n" +
            "QLHhJDDhDhgscgtjbGHTrWbrTbRmbFrm\n" +
            "CJbLvJvbwtFHqvLzwJqqqtHWTWRgDScDRSWQQjTRcWRDLT\n" +
            "mssGsMNphZMNsPPBnhSjRgdnQRdWgdjgrcDn\n" +
            "GGmBMMsffmslMGshZlMphGqCzHCbzlbvzqwzzgFJggCF\n" +
            "WCgWBphpWLQZQpgdhGdwmfbfFRVRjRTbbSFttdbSbT\n" +
            "qqrZnDNqZJDTVzRjVFbfSN\n" +
            "rPMvqJJqrJMPJnZMZZgLPgLWLggWQghwhmBh\n" +
            "CWGGzdHHmPPSmPsC\n" +
            "LqwlZwRLrPMQlMqrlbZrQRsSNsmssSNSsNcBNpgmsJ\n" +
            "lwLDQhrDMQqPGfhzGGjhGn\n" +
            "ZqDlZssCqJJMvpdBpBBmBQSMRp\n" +
            "wLgVcbgFLzTLTNNZmNNRdjdRmF\n" +
            "HZHbctWTwgVWgsfrnnPqlnsWlD\n" +
            "RSnwSPFcLnFPnRwjzctzbGNlZgNbbGdGpLhZdpgM\n" +
            "BqqBfMvTmmJqDgGNVdGVbVJJZG\n" +
            "vsTDfqBmHmMWQCwjtrHjjSFFnRSn\n" +
            "LsCmmcDHRjdtNMstwwzJ\n" +
            "TvThqfBFBNTnnndTtL\n" +
            "lvGQfbFQGblFrRccLRSSlPPVHS\n" +
            "qbLpqTHSqpbqbrPcQgjPDjcdDL\n" +
            "gnzhhBBwBWZzMglmjDrDPjvfdvQPdwtd\n" +
            "WZZzZZlZmhsMmFgRBBBzHHJpNJGVRSJVGTVpNqCH\n" +
            "JDphhGhDdGzWRBnvqqLDNLMnLw\n" +
            "gsrTHHffTHPcrPrlHCNZhvBZnZNLhPvBNwvh\n" +
            "sHVCSsSghJpSJjQh\n" +
            "JTMGlfjlTdqjnqbnqFwqmnbQ\n" +
            "PBZhBBcWRZprPZcZDDCZTZRgnnzwbbsbnvhbvznFsNFFvvNQ\n" +
            "BcWrVgCCZTDRDrlGttfVtMddSJlH\n" +
            "vwwvpVbSvnSRRmfMCmTHVHTBHB\n" +
            "QLZgDPgSDgGTMZfmTTBZ\n" +
            "QDDsQFDlzlgtJlLdFDgSJQFvvpRvjqzjRwwwzWvhvWwqjj\n" +
            "mRRTGGNNflGRGGmmgRblsGwCZwVZlZjVwjztpjZhpBCB\n" +
            "PMLLFLHPLPnLqDDLvFDrzzMjhwVCjtphBzjMhV\n" +
            "FDdSPSpLcDsNRRWSTNWN\n" +
            "STldJthdJbtTqljCRDDHmqmj\n" +
            "VVvNwwvNFssJFJPNNwVvRMCgCgDqjjjqrDqqMHqP\n" +
            "QBZwQfZwfVhtcSBtBJnT\n" +
            "TzjjPzsQTslNlNzPRVGJJJGGtTJmgJHtmTZC\n" +
            "dBDWScMBhhPGgdwwJPfw\n" +
            "SqSqbSPDBhqnMqvrrSWVNFpRVRLzVQslvpNjVL\n" +
            "bWFgFCPFtgvDZWgtChDNFJHvGVzHHpjzHnnzGzzHRR\n" +
            "qcScQbbmqdQmlQmrlcQwLmHlRRjzGHnHJnnGVjHzBHzG\n" +
            "TqQwmLmfcddfwrfCgbWCNPsZNfCb\n" +
            "pddprrtrCPdvJdMjwwwHnLwwjLWCLg\n" +
            "qhzZTmZcmRhmpFlVHcQQVwWQHVQwnH\n" +
            "lGmhfRfmBZRlmmbvDPBMvNbvJJpP\n" +
            "NsptgfGLLNwnNQSZbCvZnRnMCb\n" +
            "JldhdzwzBMCSZvrz\n" +
            "JFcdWTdwhPTFVDVmTJNqmstLqgLtLtjGGpsG\n" +
            "dVVTSgTDpHVDjgdWpdpHTZSbWGrnnvrNwzFGNrFwnNNwvh\n" +
            "CPRlMPJcMQcBcsmmLCMPrzbFfhwfrvLrNNwwGwfF\n" +
            "CRJmtbmJlQbsQlRBpZDVjTHTdjDtSjZt\n" +
            "rQVJrRFdrwDfzHQHQBTnpWTW\n" +
            "PCLbPcPCsgqCgPgLjScSqNbHTzMtWmWtzlTHmBtTlMssMT\n" +
            "cCqghSSPcvgScPbwFGdDDVZFfDhZGB\n" +
            "zrRQRdqzPHQtnMPrtzPMRRQMVBBblJJBSClBpJbpdCCbBlCC\n" +
            "hTcGwzswGwGmGfDvvfGmGNfBpllVSWbWppNCBNBVpCBClW\n" +
            "gvGFTmTgwDhTDccsTfzfmfGGQPgPPqrgRZPHnRqRZrQLnRgP\n" +
            "hvmmJllPbmCRMNGMMlNwNl\n" +
            "PFTpTVjTgpTpBRgMGMnRNHBB\n" +
            "WWrqzTTPVQDPqpjTqPJbmLtcfsQsftbLbvct\n" +
            "SzrmpjjcsjTZNzgnnNzN\n" +
            "BLHNDwBLBPLwLBhwDVLgdQCgCQGTngHQZCngZd\n" +
            "PPJBDvBVVBmppNjJjrrr\n" +
            "ZHBNQFhsqHBsgCfqtctcPvSwPqrV\n" +
            "LlnGTnJpJJTmdDpmLlmLndWfVrPvvRwDfcwwwRVwcfQtvP\n" +
            "GnbQblWmWGdTJQdTGnZHsHhZhFNsbCsjFgjC\n" +
            "hWfDzDTVndDMhddMlBWMBDfJRnRtvvSSQjCvZCtjtpJvSR\n" +
            "bGHsccFcbscsqGPHNGcrpjJZtvSRtFtQCZrjSj\n" +
            "GsbwGGwNNGLgPLwMzBzfMMVMTLdTCC\n" +
            "GBcNzTSSmGzmTLNgvwgpNCDqpDggpw\n" +
            "JRZMrJWFZZnZtJgvvjwbpbCJDd\n" +
            "rFMPRhZtZFnWrRtQGmPPDcLfmGLTfz\n" +
            "VdWnVdjhhdFjVWbndMlNLQspVMHCNVlClV\n" +
            "RSrJBRRJwJSBQpMBHLLDCL\n" +
            "TqwtRRRJzJTSqJSzSrtmqgWWhcncvPgnWbPQnbnWmb\n" +
            "VnDFpPpFssVSpFDVHbRbscCvgbMTvTCR\n" +
            "JfzqdQBfhBdddfBBGDLdGQvbrqMMcCRRMTgbqgMrbbqc\n" +
            "QDfzJNWBJLQBhmdGDzDGhQGGlFZwPtWjtFFppllSVpZZFnjj\n" +
            "qrLLNpJbJnRLNnpvQtRVhhRFCdlFFlFd\n" +
            "mmjzjvGjwPwmTsSTSQjDVlVWQjlCDthCCC\n" +
            "cSSmcTTPcSswScfSHmTSTzJqqNrnpBpqBbJLvZMrqfrL\n" +
            "NSvRZRfFvfHSZQcNJBLbzDLnrDFnhtFLFnrh\n" +
            "wmTGpmGCwsMplMsHllPlMnDLjznrgrzDjgnntznr\n" +
            "dsCVGGGwmpTGPplmCmPppVmHSSRJNfJvBNZQfWdBRJZRBZcR\n" +
            "TwQwqDPQtwNwzNDTZcnZbJvMnMMbFqZM\n" +
            "SzGSjrjLWrjHHspWVhvVVnFJbccVZcRJbllb\n" +
            "pHppszGSprhhWHLCLrsjdTtDDPfwdfwtdNfDgNCN\n" +
            "ftcvBtBFtmBlmvPFmmcczCChrgSCzzCSnCSSnGHf\n" +
            "sJddbdTDbDHdnJRggrGzGzrG\n" +
            "dppDVDZMMMsTTVsDTsTDpwVctNcvBZQPcPctqtQcHmvlvQ\n" +
            "jzbdzztbDqNqwvLvRmQZjvRH\n" +
            "FSJbFFWgJnZFLRZmHmRQ\n" +
            "TgVJTVSJGJcJlllgTMdqpdNsrztNNsNbMDDp\n" +
            "CCCVWbwVnlRbTcqSShqGhhGcnF\n" +
            "PgDBfDpMNlfgpPfNZZtcJgcqqhmmjqSmjFmhmS\n" +
            "tpfpsPrlpsPDDMDfBZrwLrVWLLLWRCdHLTwbVR\n" +
            "pjvfDGjSMpvDmDpDpSDnJmfqbPVsCMFsPqFVPqCrwrbMFV\n" +
            "NQlHtHNhZHgZZNBHhQgzPmCwbqqVFlsrPFrFCP\n" +
            "hgHtQdQchcHctHgcgNgBQdWNpmvTWvpGmLJDLGjTpLGnnjfv\n" +
            "QhgLLLmtlRqDtRGP\n" +
            "HLbnCZFWVHLZnFCJJRFrGJzDGDGJDD\n" +
            "WZHfndfMfCZbMnTVTfZhSNQQpdwSdLwhNcmdSN\n" +
            "sPwrPMgLFPFFsLZtmcclSSZDtcZs\n" +
            "qVzqdNdCnnNVVNCGmbncDBlmBlBBnRlZ\n" +
            "VTdCGVvVfffrjpfMQPwm\n" +
            "BPDldDTDPZcggjcccTdNMbbMNSQNqqjtzMbrRb\n" +
            "LvmWsfvssLGnQbQMRQqrSRnz\n" +
            "WpvsVmmpmmfpfJGrHfVCHVvmcDgpDlZphgFgdhclhdgdBlgF\n" +
            "VGwHbNzMMrzHbbHChhqgCqPNghgCqW\n" +
            "ZJVBvBvZWqvRvggP\n" +
            "JBJlBlBZcsBfcJVrHnLwQQGzLQMc\n" +
            "gBWfBPPPfhvVWFfSVfVdjjbvTvwwQppHcHcctTcQTHcZ\n" +
            "DnNnMJMqMJzqchbZtTQQrb\n" +
            "llRmNLDLDGlCsWSFCffWdshd\n" +
            "LpNMZZpqqpfTTwNqLZwGsZqZbdHRHbHGddnCBHRcmzGmmCdG\n" +
            "JFRtRlVStjPlhtjbBzBncmVWdzWBnb\n" +
            "rPhhSlrvQlFFFPgtJlJtFlhlDNTwRMfZTZfDZNrspZLMMsrq\n" +
            "zBLjLFBjLjmHWlzNZlzVCC\n" +
            "dcJrdfddbllJbdMTwDNMZWNVwVDwHT\n" +
            "gRcgJbcbqfgbftdjlqLhFFLPPhGBjm\n" +
            "WfBgBRzQGNNQqmmqZN\n" +
            "nFjCjCpLbtpPJtCDDnCDJpzncrSVbmdVqbhhdqNbSSmrdVSq\n" +
            "CLPJpDLlLlFDpFjjsGRsBGRfWwsHHglz\n" +
            "lSlSlpCRSsWTRLTlWRvlmMrBPjBPjpqrrmqPJMPZ\n" +
            "DDzbhVhQhDGzhQnGGfnHHQGBPZjMqJjBJMBVJmqMdrqqdT\n" +
            "NNGQbFwnHzNzwbQwFnwbfsLCLtsvLsWggFslsTggSc\n" +
            "nvzPvCnlvtwCrZWmWwvvZCQfbbfQfGbqSJJGmqGSFSbJ\n" +
            "LhTBWdsMNNRgNcgDWsDNcVSfQqJGFSFJqSSddQGSJF\n" +
            "HNgchHcWDRNhTNMWwtPrtZZjnHzrnvCz\n" +
            "djhnzRghMMVCBfhh\n" +
            "qjQTrTPQJCDDqBDJ\n" +
            "LQvGrLjTHLjNNPPTpQgtztSmmbFgmgLbFnmL\n" +
            "FRDNFBBRRVFFmbLZHPZBZvvH\n" +
            "QnhgMllglJTdGgJnhLQQJpZpvwZHpwsPTwpbsZHmsH\n" +
            "lnhnQGrMgthMlntlGfQhgWWcRSDcVCrLWzRSrRFDRN\n" +
            "PqrrrRnPBbrVhVqFrFVRPVhZLvNSNvLZcQvtJfRvNScJNJ\n" +
            "dDzWwwCTmmdwdddpDLWQZMSSMfSJtcWJfQSQZN\n" +
            "CCwmTdjsClVjFjnLBl\n" +
            "srjCvjPmQVlPjFPmQmPrdHHZhvHZDqHhDDwHHqfB\n" +
            "pLcnJQNQMZpqZDDZ\n" +
            "WNRbtNJgRPjjQVmz\n" +
            "NJJRmjmJbbJfqSVMNHFCSFzLLlrLLrFHTz\n" +
            "QvnsQGvBwWwQvgRHlGGDFPFCGlrR\n" +
            "QhvwBvBctBccZWZNRNmVfjpmjJjb\n" +
            "RMmGGMLRRCFmRPPfGFpGPFPJWZQWctrtlQvZvltfrQWcWWBq\n" +
            "gggwjjbjwwbZtwZBBcmQQv\n" +
            "SdNbDDVSgPMFmPzdMm\n" +
            "nZhnNZDnZPmZPWbppPpMlvRlzvrtMmRtqRzRfq\n" +
            "HcFwsCQLVQwFwLtLbvtzrlrLtt\n" +
            "GsgCFCgCQHHCVHsFQHcFdDPDbJDZTpZDbWJPNWWZDd\n" +
            "BBrBrGlGpgGjsNhlBlpBwpfSwZJdQwfcZwvSQnnn\n" +
            "LvWvHLmmVJQQHfQH\n" +
            "RPLRMvqFTbRTjGBhjNFsslls\n" +
            "cNZZZmZDcDDJmhzzrrlHtSbvgjSvgfPSWvPfjShv\n" +
            "VBwnndnVCqbqpRRpnspnqRWtGgWSSgvFBSGGSWgtGGSP\n" +
            "LqCMnTLVRwCRCpRLpbHDNzMMNcmmHNHQJQ\n" +
            "MMqDtnVnBlHtZvtB\n" +
            "WLWrWgdWwdrLCTFCwLlbbsJsJQsbQlQzlvrB\n" +
            "jFSvTdjfnfRmVcRR\n" +
            "ZLGqnvnqLzvbGRMfcRpwMpdV\n" +
            "fgfNNfgHHjVmRcVdgM\n" +
            "HsWDCDfCQCZBBZnvWtLq\n" +
            "bTZjqflqZhcrlczGzppGNgjmFNnp\n" +
            "PmmRSWWDMBQVNpWFznGF\n" +
            "SStRBDSCCSSSwPBwBDBwPmZhZlfZhqHTsTfltHHZfsHH\n" +
            "GbNbsSptQGqsdJCzsddcgzzv\n" +
            "DHRRnmWWmZnmRhllnHnnnMLvvLgcTVvjVhCTvgzcJgLj\n" +
            "RnWMlDZRlnHlmHWBFwGQqNGGPNQzPGqFwz\n" +
            "vSGvHpJnBLbGHBNCgfDzzChDgbCfzT\n" +
            "wFRslqmqTRgggQghPmQf\n" +
            "qjRFMjWqNNMMGHTL\n" +
            "fWGcQGGSRFQZhttZJfSSJflDDrwdClljVrNDdrdCFBCr\n" +
            "MTgvLLPPnHzMbDwdlNbMBwMM\n" +
            "mnTvnnPTcNmmJJWN\n" +
            "qqbbQQnbWrqGgnWqvZpVzMCZjCgfjZCSVM\n" +
            "ldcmDPDhmlFBHPDddLBVFDHLppZpjSCjjNfwNMwCpSMwhCMp\n" +
            "FtDdsHPcHmdHVPLtHsdtBHQnsbvnTRRTRsRRqbqvqWnJ\n" +
            "hhtBtPrgbbhhgjZjjCCHHNpNDHpffHWCvr\n" +
            "LGFLVwswsJMSgFwMMpddSvpHCCdDdvCpvm\n" +
            "sGsFsQLsVsLFnnFTJQthjcjQqhRcBZZtRg";
}
