public class InputDay2 {

    public static final String SMALL_INPUT = "";
    public static final String LARGE_INPUT = "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "A X\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "A Y\n" +
            "A Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "B Y\n" +
            "A X\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Y\n" +
            "A Y\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B Y\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "A Y\n" +
            "A X\n" +
            "C Z\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "C X\n" +
            "A Y\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "A Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A Y\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "B X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "A Y\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Z\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "B X\n" +
            "A Y\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "C Z\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "A Y\n" +
            "A X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Y\n" +
            "B X\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "A Y\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "A Y\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "A Y\n" +
            "C Z\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "A Y\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "B Y\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "A Y\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "A X\n" +
            "C Y\n" +
            "A Y\n" +
            "A Z\n" +
            "A X\n" +
            "A Y\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "A Y\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "A Y\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "A Y\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "A Y\n" +
            "A Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "A Y\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Y\n" +
            "B Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "A Y\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "C Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Y\n" +
            "A X\n" +
            "A Z\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "A Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "A Y\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "A Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "C Y\n" +
            "B Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "A X\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "B Y\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Y\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A Y\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "A Y\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "C Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "B Y\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "A Y\n" +
            "B X\n" +
            "A X\n" +
            "B Y\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "A Y\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "B X\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "B Y\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "A X\n" +
            "B Y\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "B X\n" +
            "A Y\n" +
            "A Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "A Y\n" +
            "A X\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "A Y\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B X\n" +
            "A X\n" +
            "A Y\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "A Y\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "A Y\n" +
            "B Y\n" +
            "A Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "A Y\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A Y\n" +
            "A Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "A Y\n" +
            "B Z\n" +
            "A X\n" +
            "A Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "A Y\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "A Z\n" +
            "B Y\n" +
            "A X\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "A Y\n" +
            "B X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "B X\n" +
            "A Y\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "B Y\n" +
            "A Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "A Y\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "A Y\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "A Y\n" +
            "A X\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "B X\n" +
            "A Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "A Y\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "A Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "A Y\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Y\n" +
            "A Z\n" +
            "B Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "A Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "A Y\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "A Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Y\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "A Y\n" +
            "A X\n" +
            "A Y\n" +
            "B Y\n" +
            "A Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "B X\n" +
            "A Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Z\n" +
            "A Y\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "B Y\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "A Y\n" +
            "C Y\n" +
            "C X\n" +
            "A Y\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "A X\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "A Y\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Y\n" +
            "B X\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "B Y\n" +
            "A Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "A Y\n" +
            "A X\n" +
            "A Z\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "A Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "A Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Y\n" +
            "C X\n" +
            "A Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "A Y\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "A Y\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "B X\n" +
            "A Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "A Y\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "A Z\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "A Z\n" +
            "A Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "B Z\n" +
            "A Y\n" +
            "A Y\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "C Z\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Y\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "A Y\n" +
            "B Z\n" +
            "B X\n" +
            "A Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Z\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Y\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B X\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "A Y\n" +
            "B X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "B X\n" +
            "C Y\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A Y\n" +
            "A Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "B Y\n" +
            "B X\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "A Z\n" +
            "A X\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "A Y\n" +
            "B X\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "B X\n" +
            "A X\n" +
            "A Y\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "C Z\n" +
            "C X\n" +
            "B X\n" +
            "A Z\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "C Y";;
}
